package com.airsofka.authentication.domain.user.events;

public enum EventsEnum {
  AGGREGATED_BOOKING,
  AUTHENTICATED_USER,
  AUTHENTICATED_GOOGLE_USER,
  LOGGED_OUT_USER,
  TOGGLED_USER,
  MARKED_AS_FREQUENT_USER,
  MODIFIED_USER,
  REGISTERED_USER,
  REGISTERED_GOOGLE_USER
}
